#!/bin/sh
#
# wlan0        Starts WiFi.
#

start() {
        printf "Starting WiFi AP: "
        ifconfig wlan0 up
        ifconfig wlan0 10.10.20.1
        udhcpd -f /etc/udhcpd.conf &
        hostapd -B /etc/hostapd.conf
        [ $? -eq 0 ] && echo "OK" || echo "ERROR"
}
stop() {
        printf "Stopping WiFi AP: "
        killall udhcpd
        killall hostapd
	ifconfig wlan0 down
        [ $? -eq 0 ] && echo "OK" || echo "ERROR"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
